"use client";

import { useMemo, useState } from "react";
import { Field, Result, SelectField, fmt, number } from "./ToolUI";

const demoText = "Gute Texte beantworten eine konkrete Frage. Kurze Sätze helfen beim Lesen, doch abwechslungsreiche Formulierungen bleiben wichtig.";
const words = (text: string) => text.toLocaleLowerCase("de").match(/[a-zäöüß0-9]+/gi) ?? [];
const copy = (value: string) => navigator.clipboard.writeText(value);
function Area({ label, value, onChange, rows = 7, placeholder, readOnly = false }: { label: string; value: string; onChange: (v: string) => void; rows?: number; placeholder?: string; readOnly?: boolean }) {
  return <label className="field"><span>{label}</span><textarea rows={rows} value={value} placeholder={placeholder} readOnly={readOnly} onChange={(e) => onChange(e.target.value)} /></label>;
}
function CodeResult({ value, label = "Erzeugter Code" }: { value: string; label?: string }) {
  return <div className="generated-output"><div><strong>{label}</strong><button type="button" onClick={() => copy(value)}>Kopieren</button></div><pre><code>{value}</code></pre></div>;
}
const gcd = (a: number, b: number): number => b ? gcd(b, a % b) : Math.abs(a || 1);
const gradeAt = (percent: number, pass: number) => percent >= pass ? Math.max(1, Math.min(4, 1 + 3 * (100 - percent) / Math.max(1, 100 - pass))) : Math.min(6, 4 + 2 * (pass - percent) / Math.max(1, pass));

function WeightedGrades() {
  const [rows, setRows] = useState([{ note: "2", gewicht: "1" }, { note: "1.7", gewicht: "2" }, { note: "2.3", gewicht: "1" }]);
  const [target, setTarget] = useState("2"); const [nextWeight, setNextWeight] = useState("1");
  const totalWeight = rows.reduce((s, r) => s + Math.max(0, number(r.gewicht)), 0);
  const points = rows.reduce((s, r) => s + number(r.note) * Math.max(0, number(r.gewicht)), 0);
  const average = totalWeight ? points / totalWeight : 0;
  const needed = number(nextWeight) ? (number(target) * (totalWeight + number(nextWeight)) - points) / number(nextWeight) : 0;
  const update = (i: number, key: "note" | "gewicht", value: string) => setRows((old) => old.map((r, x) => x === i ? { ...r, [key]: value } : r));
  return <><div className="editable-list">{rows.map((row, i) => <div className="editable-row" key={i}><Field label={`Note ${i + 1}`} value={row.note} onChange={(v) => update(i, "note", v)} min="1" max="6" step="0.1" /><Field label="Gewichtung" value={row.gewicht} onChange={(v) => update(i, "gewicht", v)} min="0" step="0.5" /><button aria-label={`Note ${i + 1} entfernen`} disabled={rows.length < 2} onClick={() => setRows((old) => old.filter((_, x) => x !== i))}>×</button></div>)}</div><button className="secondary-button" onClick={() => setRows((old) => [...old, { note: "2", gewicht: "1" }])}>+ Note hinzufügen</button><Result label="Gewichteter Durchschnitt" value={fmt(average, 2)} detail={`Summe der Gewichtungen: ${fmt(totalWeight, 1)}`} /><div className="sub-tool"><h3>Zielnote planen</h3><div className="field-grid"><Field label="Gewünschter Schnitt" value={target} onChange={setTarget} min="1" max="6" step="0.1" /><Field label="Gewichtung der nächsten Note" value={nextWeight} onChange={setNextWeight} min="0.1" step="0.5" /></div><p className={`status-line ${needed < 1 || needed > 6 ? "warn" : "ok"}`}>{needed < 1 ? "Das Ziel ist bereits besser als mit einer weiteren 1,0 nötig." : needed > 6 ? "Das Ziel ist mit nur dieser einen weiteren Note nicht erreichbar." : `Benötigte nächste Note: ${fmt(needed, 2)} oder besser`}</p></div></>;
}

function GradeKey({ single = false }: { single?: boolean }) {
  const [max, setMax] = useState("100"), [pass, setPass] = useState("50"), [got, setGot] = useState("73");
  const maximum = Math.max(1, number(max)), passPct = Math.min(99, Math.max(1, number(pass))), pct = 100 * number(got) / maximum;
  if (single) return <><div className="field-grid three"><Field label="Erreichte Punkte" value={got} onChange={setGot} min="0" /><Field label="Gesamtpunkte" value={max} onChange={setMax} min="1" /><Field label="Bestehensgrenze" value={pass} onChange={setPass} suffix="%" min="1" max="99" /></div><Result label="Ergebnis" value={`${fmt(pct, 1)} % · Note ${fmt(gradeAt(pct, passPct), 1)}`} detail="Lineare Orientierung – offizielle Vorgabe prüfen" /></>;
  const thresholds = [1, 2, 3, 4, 5, 6].map((g) => { const p = g <= 4 ? 100 - (g - 1) * (100 - passPct) / 3 : g === 5 ? passPct / 2 : 0; return { g, p, points: Math.ceil(maximum * p / 100) }; });
  return <><div className="field-grid"><Field label="Maximal erreichbare Punkte" value={max} onChange={setMax} min="1" /><Field label="Bestehensgrenze" value={pass} onChange={setPass} suffix="%" min="1" max="99" /></div><div className="result-table"><table><thead><tr><th>Note</th><th>ab Prozent</th><th>ab Punkten</th></tr></thead><tbody>{thresholds.map((r) => <tr key={r.g}><td>{r.g}</td><td>{fmt(r.p, 1)} %</td><td>{r.points} von {maximum}</td></tr>)}</tbody></table></div><p className="privacy-note">Linearer Vorschlag. Die verbindlichen Grenzen legt die zuständige Schule oder Lehrkraft fest.</p></>;
}

function Fractions() {
  const [an, setAn] = useState("2"), [ad, setAd] = useState("3"), [bn, setBn] = useState("1"), [bd, setBd] = useState("4"), [op, setOp] = useState("+");
  let n = 0, d = 1; const a = number(an), b = number(ad), c = number(bn), e = number(bd); let step = "";
  if (b && e) { if (op === "+") { n = a * e + c * b; d = b * e; step = `${an} × ${bd} + ${bn} × ${ad}`; } if (op === "−") { n = a * e - c * b; d = b * e; step = `${an} × ${bd} − ${bn} × ${ad}`; } if (op === "×") { n = a * c; d = b * e; step = `${an} × ${bn} / (${ad} × ${bd})`; } if (op === "÷" && c) { n = a * e; d = b * c; step = `${an} × ${bd} / (${ad} × ${bn})`; } }
  const divisor = gcd(n, d), rn = n / divisor, rd = d / divisor; const invalid = !b || !e || (op === "÷" && !c);
  return <><div className="fraction-line"><div><Field label="Zähler A" value={an} onChange={setAn} /><Field label="Nenner A" value={ad} onChange={setAd} /></div><SelectField label="Rechenart" value={op} onChange={setOp} options={["+", "−", "×", "÷"].map((x) => ({ value: x, label: x }))} /><div><Field label="Zähler B" value={bn} onChange={setBn} /><Field label="Nenner B" value={bd} onChange={setBd} /></div></div><Result label="Gekürztes Ergebnis" value={invalid ? "Nicht definiert" : rd === 1 ? String(rn) : `${rn} / ${rd}`} detail={invalid ? "Nenner dürfen nicht 0 sein; durch 0 kann nicht geteilt werden." : `${step} = ${n}/${d}; gekürzt durch ${divisor}`} /></>;
}

function Equation() { const [a, setA] = useState("3"), [b, setB] = useState("6"), [c, setC] = useState("18"); const av = number(a), bv = number(b), cv = number(c); const x = av ? (cv - bv) / av : 0; return <><p className="equation-preview">{a || "a"}x {bv >= 0 ? "+" : "−"} {fmt(Math.abs(bv))} = {c || "c"}</p><div className="field-grid three"><Field label="a" value={a} onChange={setA} /><Field label="b" value={b} onChange={setB} /><Field label="c" value={c} onChange={setC} /></div><Result label="Lösung" value={av ? `x = ${fmt(x, 4)}` : bv === cv ? "Unendlich viele Lösungen" : "Keine Lösung"} detail={av ? `1. ${fmt(av)}x = ${fmt(cv)} − (${fmt(bv)}) = ${fmt(cv - bv)} · 2. x = ${fmt(cv - bv)} ÷ ${fmt(av)}` : "Wenn a = 0 ist, enthält die Gleichung kein x."} /></>; }

function LearningPlan() {
  const [initial] = useState(() => { const today = new Date(); today.setHours(12, 0, 0, 0); const soon = new Date(today); soon.setDate(soon.getDate() + 35); return { base: today.getTime(), date: soon.toISOString().slice(0, 10) }; });
  const [date, setDate] = useState(initial.date), [hours, setHours] = useState("6"), [topics, setTopics] = useState("Grundlagen wiederholen\nKapitel 1–3\nÜbungsaufgaben\nProbeklausur");
  const days = Math.max(1, Math.ceil((new Date(`${date}T12:00:00`).getTime() - initial.base) / 86400000)), weeks = Math.max(1, Math.ceil(days / 7)), list = topics.split("\n").map((x) => x.trim()).filter(Boolean), usable = number(hours) * .8;
  return <><div className="field-grid"><Field label="Prüfungstermin" value={date} onChange={setDate} type="date" /><Field label="Lernstunden pro Woche" value={hours} onChange={setHours} min="0.5" step="0.5" /></div><Area label="Themen – eines pro Zeile" value={topics} onChange={setTopics} rows={5} /><Result label="Verfügbare Lernzeit" value={`${fmt(number(hours) * weeks, 1)} Stunden in ${weeks} Wochen`} detail={`${fmt(usable * weeks, 1)} Std. Stoff · ${fmt(number(hours) * weeks * .2, 1)} Std. Wiederholung`} /><div className="plan-grid">{Array.from({ length: weeks }, (_, i) => <article key={i}><strong>Woche {i + 1}</strong><span>{i === weeks - 1 ? "Wiederholen, Lücken schließen, Probeprüfung" : list.length ? list[i % list.length] : "Thema eintragen"}</span><small>{fmt(number(hours), 1)} Std. einplanen</small></article>)}</div></>;
}

function Flashcards() { const [input, setInput] = useState("Was ist Photosynthese? | Umwandlung von Lichtenergie in chemische Energie.\nWas ist ein Bruch? | Ein Anteil eines Ganzen mit Zähler und Nenner."), [shuffle, setShuffle] = useState(false); const cards = input.split("\n").map((line) => line.split("|").map((x) => x.trim())).filter((x) => x[0] && x[1]); const shown = shuffle ? [...cards].sort((a, b) => (a[0] > b[0] ? -1 : 1)) : cards; return <><Area label="Eine Karte pro Zeile: Frage | Antwort" value={input} onChange={setInput} /><div className="tool-actions"><button className="secondary-button" onClick={() => setShuffle((x) => !x)}>{shuffle ? "Originalreihenfolge" : "Karten mischen"}</button><button className="primary-button" onClick={() => window.print()}>Karteikarten drucken</button></div><div className="flashcards">{shown.map((card, i) => <article key={`${card[0]}-${i}`}><small>Karte {i + 1}</small><strong>{card[0]}</strong><span>{card[1]}</span></article>)}</div></>;
}

const syllables = (word: string) => Math.max(1, (word.toLowerCase().replace(/[^a-zäöüß]/g, "").match(/[aeiouyäöü]+/g) ?? []).length);
function Readability() { const [text, setText] = useState(demoText); const ws = words(text), sentences = text.split(/[.!?]+/).map((x) => x.trim()).filter(Boolean), score = ws.length && sentences.length ? 180 - ws.length / sentences.length - 58.5 * ws.reduce((s, w) => s + syllables(w), 0) / ws.length : 0; const label = score >= 80 ? "sehr leicht" : score >= 60 ? "gut verständlich" : score >= 40 ? "anspruchsvoll" : "sehr schwer"; return <><Area label="Deutscher Text" value={text} onChange={setText} rows={10} /><Result label="Flesch-Lesewert" value={`${fmt(score, 0)} · ${label}`} detail={`${ws.length} Wörter · ${sentences.length} Sätze · Ø ${fmt(ws.length / Math.max(1, sentences.length), 1)} Wörter je Satz`} /><div className="findings"><strong>Lange Sätze ab 20 Wörtern</strong>{sentences.filter((s) => words(s).length >= 20).length ? sentences.filter((s) => words(s).length >= 20).map((s) => <p key={s}>{s}</p>) : <p>Keine auffällig langen Sätze gefunden.</p>}</div></>; }

function diffTokens(a: string, b: string) { const x = a.match(/\S+|\s+/g) ?? [], y = b.match(/\S+|\s+/g) ?? []; if (x.length * y.length > 160000) return { old: a, next: b, limited: true }; const dp = Array.from({ length: x.length + 1 }, () => new Uint16Array(y.length + 1)); for (let i = x.length - 1; i >= 0; i--) for (let j = y.length - 1; j >= 0; j--) dp[i][j] = x[i] === y[j] ? dp[i + 1][j + 1] + 1 : Math.max(dp[i + 1][j], dp[i][j + 1]); const old: React.ReactNode[] = [], next: React.ReactNode[] = []; let i = 0, j = 0; while (i < x.length || j < y.length) { if (x[i] === y[j]) { old.push(x[i]); next.push(y[j]); i++; j++; } else if (j < y.length && (i === x.length || dp[i][j + 1] >= dp[i + 1][j])) { next.push(<mark className="added" key={`a${j}`}>{y[j]}</mark>); j++; } else { old.push(<mark className="removed" key={`r${i}`}>{x[i]}</mark>); i++; } } return { old, next, limited: false }; }
function TextDiff() { const [a, setA] = useState("Das ist der erste kurze Text."), [b, setB] = useState("Das ist der überarbeitete, deutlichere Text."); const result = useMemo(() => diffTokens(a, b), [a, b]); return <><div className="field-grid"><Area label="Alte Version" value={a} onChange={setA} /><Area label="Neue Version" value={b} onChange={setB} /></div>{result.limited ? <p className="status-line warn">Der Text ist für den detaillierten Vergleich zu lang. Bitte abschnittsweise vergleichen.</p> : <div className="diff-grid"><article><strong>Entfernt</strong><p>{result.old}</p></article><article><strong>Hinzugefügt</strong><p>{result.next}</p></article></div>}</>; }

const fillers = new Set(["also", "eigentlich", "irgendwie", "quasi", "halt", "eben", "sozusagen", "gewissermaßen", "natürlich", "wirklich", "sehr", "vielleicht", "wohl", "einfach"]);
function Fillers() { const [text, setText] = useState("Eigentlich ist dieser Text wirklich sehr einfach, aber irgendwie wiederholt der Text einige Wörter."); const list = words(text); const counts = new Map<string, number>(); list.forEach((w) => counts.set(w, (counts.get(w) ?? 0) + 1)); const fill = [...counts].filter(([w]) => fillers.has(w)).sort((a, b) => b[1] - a[1]), repeats = [...counts].filter(([w, n]) => w.length > 3 && n > 1 && !fill.some(([f]) => f === w)).sort((a, b) => b[1] - a[1]).slice(0, 12); return <><Area label="Text untersuchen" value={text} onChange={setText} rows={10} /><div className="analysis-columns"><article><strong>Füllwörter</strong>{fill.length ? fill.map(([w, n]) => <span key={w}>{w} <b>{n}×</b></span>) : <p>Keine Wörter aus der Prüfliste.</p>}</article><article><strong>Wiederholungen</strong>{repeats.length ? repeats.map(([w, n]) => <span key={w}>{w} <b>{n}×</b></span>) : <p>Keine auffälligen Wiederholungen.</p>}</article></div></>; }

function Cleaner() { const [input, setInput] = useState("Dieser  Text hat   zu viele Leerzeichen.\n\n\nUnd unnötige Leerzeilen."), [lines, setLines] = useState(false), [quotes, setQuotes] = useState(true); let output = input.replace(/[ \t]+/g, " ").replace(/ *\n */g, "\n").replace(/\n{3,}/g, "\n\n"); if (lines) output = output.replace(/([^\n.!?:;])\n(?=[^\n])/g, "$1 "); if (quotes) output = output.replace(/[“”„]/g, '"').replace(/[‘’]/g, "'").replace(/…/g, "..."); return <><Area label="Unbereinigter Text" value={input} onChange={setInput} rows={8} /><div className="check-grid"><label><input type="checkbox" checked={lines} onChange={(e) => setLines(e.target.checked)} /> Einzelne Zeilen zusammenführen</label><label><input type="checkbox" checked={quotes} onChange={(e) => setQuotes(e.target.checked)} /> Anführungszeichen vereinheitlichen</label></div><Area label="Bereinigtes Ergebnis" value={output} onChange={() => undefined} rows={8} readOnly /><button className="primary-button" onClick={() => copy(output)}>Ergebnis kopieren</button></>; }

function LetterCase() { const [input, setInput] = useState("Ein Beispiel für deine Überschrift"), [mode, setMode] = useState("upper"); const output = mode === "upper" ? input.toLocaleUpperCase("de") : mode === "lower" ? input.toLocaleLowerCase("de") : mode === "sentence" ? input.toLocaleLowerCase("de").replace(/(^|[.!?]\s+)([a-zäöü])/g, (_, a, b) => a + b.toLocaleUpperCase("de")) : input.toLocaleLowerCase("de").replace(/(^|\s)([a-zäöü])/g, (_, a, b) => a + b.toLocaleUpperCase("de")); return <><Area label="Text" value={input} onChange={setInput} /><div className="segmented wrap">{[["upper", "GROSS"], ["lower", "klein"], ["sentence", "Satzanfänge"], ["title", "Überschrift"]].map(([v, l]) => <button className={mode === v ? "active" : ""} onClick={() => setMode(v)} key={v}>{l}</button>)}</div><Area label="Ergebnis" value={output} onChange={() => undefined} readOnly /><button className="primary-button" onClick={() => copy(output)}>Ergebnis kopieren</button></>; }

function Citation() { const [type, setType] = useState("web"), [style, setStyle] = useState("apa"), [author, setAuthor] = useState("Mustermann, Erika"), [title, setTitle] = useState("Titel der Quelle"), [year, setYear] = useState("2026"), [publisher, setPublisher] = useState("Herausgeber"), [url, setUrl] = useState("https://example.org"), [access, setAccess] = useState(new Date().toISOString().slice(0, 10)); const date = access ? new Date(`${access}T12:00:00`).toLocaleDateString("de-DE") : ""; const result = style === "apa" ? `${author} (${year || "o. D."}). ${title}. ${publisher}${type === "web" ? `. ${url}` : "."}` : style === "harvard" ? `${author} (${year || "o. J."}): ${title}. ${publisher}${type === "web" ? `, online unter: ${url} (abgerufen am ${date}).` : "."}` : `${author}: ${title}, ${publisher} ${year || "o. J."}${type === "web" ? `, ${url} (Abruf: ${date}).` : "."}`; return <><div className="field-grid"><SelectField label="Quellentyp" value={type} onChange={setType} options={[{ value: "web", label: "Website" }, { value: "book", label: "Buch" }, { value: "article", label: "Fachartikel" }]} /><SelectField label="Zitierstil" value={style} onChange={setStyle} options={[{ value: "apa", label: "APA (vereinfacht)" }, { value: "harvard", label: "Harvard (deutsch)" }, { value: "footnote", label: "Deutsche Fußnote" }]} /><Field label="Autor/in" value={author} onChange={setAuthor} type="text" /><Field label="Jahr" value={year} onChange={setYear} type="text" /><Field label="Titel" value={title} onChange={setTitle} type="text" /><Field label="Verlag / Website / Zeitschrift" value={publisher} onChange={setPublisher} type="text" />{type === "web" ? <><Field label="URL" value={url} onChange={setUrl} type="url" /><Field label="Abrufdatum" value={access} onChange={setAccess} type="date" /></> : null}</div><CodeResult label="Quellenangabe" value={result} /></>; }

function Snippet() { const [title, setTitle] = useState("Sofort verständlicher Seitentitel"), [url, setUrl] = useState("https://www.example.de/passende-seite"), [desc, setDesc] = useState("Eine klare Beschreibung erklärt den Inhalt und zeigt, warum sich ein Klick auf diese Seite lohnt."); return <><div className="field-grid"><Field label="Seitentitel" value={title} onChange={setTitle} type="text" /><Field label="URL" value={url} onChange={setUrl} type="url" /></div><Area label="Meta-Description" value={desc} onChange={setDesc} rows={4} /><div className="length-hints"><span className={title.length > 60 ? "bad" : "good"}>Title: {title.length} Zeichen</span><span className={desc.length > 160 ? "bad" : "good"}>Description: {desc.length} Zeichen</span></div><div className="serp-preview"><cite>{url}</cite><strong>{title || "Seitentitel"}</strong><p>{desc || "Meta-Description"}</p></div><p className="privacy-note">Google misst überwiegend Pixel statt Zeichen und kann Texte abhängig von der Suchanfrage umschreiben.</p></>; }

const stopwords = new Set("der die das den dem des ein eine einer eines und oder aber ist sind war wie von zu im in am an auf für mit als sich es auch nicht bei durch aus wird werden dieser diese dieses ihr ihre wir sie man".split(" "));
function KeywordDensity() { const [text, setText] = useState(demoText + " Gute Inhalte beantworten Fragen vollständig und verständlich."); const list = words(text).filter((w) => !stopwords.has(w) && w.length > 2), counts = new Map<string, number>(), pairs = new Map<string, number>(); list.forEach((w, i) => { counts.set(w, (counts.get(w) ?? 0) + 1); if (list[i + 1]) { const p = `${w} ${list[i + 1]}`; pairs.set(p, (pairs.get(p) ?? 0) + 1); } }); const top = [...counts].sort((a, b) => b[1] - a[1]).slice(0, 12), topPairs = [...pairs].filter(([, n]) => n > 1).sort((a, b) => b[1] - a[1]).slice(0, 8); return <><Area label="Text analysieren" value={text} onChange={setText} rows={10} /><div className="analysis-columns"><article><strong>Häufigste Begriffe</strong>{top.map(([w, n]) => <span key={w}>{w}<b>{n}× · {fmt(100 * n / Math.max(1, list.length), 1)} %</b></span>)}</article><article><strong>Wortpaare</strong>{topPairs.length ? topPairs.map(([w, n]) => <span key={w}>{w}<b>{n}×</b></span>) : <p>Noch keine Wortpaare wiederholt.</p>}</article></div></>; }

function Onpage() { const [html, setHtml] = useState('<html lang="de"><head><title>Beispieltitel</title><meta name="description" content="Klare Beschreibung der Beispielseite."></head><body><h1>Hauptüberschrift</h1><h2>Unterthema</h2><img src="bild.jpg" alt="Beschreibung"><a href="/kontakt">Kontakt</a></body></html>'); const findings = useMemo(() => { if (typeof DOMParser === "undefined") return []; const doc = new DOMParser().parseFromString(html, "text/html"), title = doc.querySelector("title")?.textContent?.trim() ?? "", desc = doc.querySelector('meta[name="description"]')?.getAttribute("content") ?? "", h1 = doc.querySelectorAll("h1"), images = [...doc.querySelectorAll("img")], links = [...doc.querySelectorAll("a[href]")]; return [{ ok: title.length >= 20 && title.length <= 65, text: `Title: ${title.length ? `${title.length} Zeichen` : "fehlt"}` }, { ok: desc.length >= 70 && desc.length <= 170, text: `Meta-Description: ${desc.length ? `${desc.length} Zeichen` : "fehlt"}` }, { ok: h1.length === 1, text: `H1: ${h1.length} gefunden` }, { ok: images.every((img) => img.hasAttribute("alt")), text: `Alt-Texte: ${images.filter((i) => i.hasAttribute("alt")).length} von ${images.length}` }, { ok: links.length > 0, text: `Links: ${links.length} gefunden` }, { ok: !!doc.documentElement.getAttribute("lang"), text: `Dokumentsprache: ${doc.documentElement.getAttribute("lang") || "fehlt"}` }]; }, [html]); return <><Area label="HTML der Seite" value={html} onChange={setHtml} rows={14} /><div className="check-results">{findings.map((f) => <p className={f.ok ? "ok" : "warn"} key={f.text}><b>{f.ok ? "✓" : "!"}</b>{f.text}</p>)}</div><p className="privacy-note">Das Tool prüft nur den eingefügten Quelltext, nicht Serverstatus, JavaScript-Rendering, Ladezeit oder die gesamte Website.</p></>; }

const makeSlug = (value: string, remove: boolean) => { let result = value.toLocaleLowerCase("de").replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); if (remove) result = result.split("-").filter((w) => !stopwords.has(w)).join("-"); return result; };
function Slug() { const [input, setInput] = useState("Wie erstelle ich eine gute SEO URL?"), [remove, setRemove] = useState(true); const result = makeSlug(input, remove); return <><Field label="Überschrift" value={input} onChange={setInput} type="text" /><label className="check-row"><input type="checkbox" checked={remove} onChange={(e) => setRemove(e.target.checked)} /> Häufige Füllwörter entfernen</label><Result label="URL-Slug" value={`/${result || "slug"}`} detail={`${result.length} Zeichen · ${result.split("-").filter(Boolean).length} Bestandteile`} /><button className="primary-button" onClick={() => copy(result)}>Slug kopieren</button></>; }

const esc = (v: string) => v.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
function MetaTags() { const [title, setTitle] = useState("Seitentitel"), [desc, setDesc] = useState("Eine konkrete Beschreibung der Seite."), [canonical, setCanonical] = useState("https://www.example.de/seite"), [robots, setRobots] = useState("index, follow"); const output = `<title>${esc(title)}</title>\n<meta name="description" content="${esc(desc)}">\n<link rel="canonical" href="${esc(canonical)}">\n<meta name="robots" content="${robots}">`; return <><div className="field-grid"><Field label="Title" value={title} onChange={setTitle} type="text" /><Field label="Canonical URL" value={canonical} onChange={setCanonical} type="url" /></div><Area label="Meta-Description" value={desc} onChange={setDesc} rows={4} /><SelectField label="Robots" value={robots} onChange={setRobots} options={[{ value: "index, follow", label: "Indexieren und Links folgen" }, { value: "noindex, follow", label: "Nicht indexieren, Links folgen" }, { value: "noindex, nofollow", label: "Nicht indexieren, Links nicht folgen" }]} /><div className="length-hints"><span className={title.length <= 60 ? "good" : "bad"}>Title {title.length}/60</span><span className={desc.length <= 160 ? "good" : "bad"}>Description {desc.length}/160</span></div><CodeResult value={output} /></>; }

function FaqSchema() { const [input, setInput] = useState("Was kostet das Tool? | Es ist kostenlos.\nWerden Daten hochgeladen? | Nein, die Verarbeitung erfolgt lokal."); const entities = input.split("\n").map((line) => line.split("|").map((x) => x.trim())).filter((x) => x[0] && x[1]).map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })); const json = JSON.stringify({ "@context": "https://schema.org", "@type": "FAQPage", mainEntity: entities }, null, 2).replace(/</g, "\\u003c"); const output = `<script type="application/ld+json">\n${json}\n</script>`; return <><Area label="Eine FAQ pro Zeile: Frage | Antwort" value={input} onChange={setInput} rows={8} /><p className={`status-line ${entities.length ? "ok" : "warn"}`}>{entities.length} vollständige FAQ{entities.length === 1 ? "" : "s"} erkannt</p><CodeResult value={output} /></>; }

function OpenGraph() { const [title, setTitle] = useState("Titel für geteilte Links"), [desc, setDesc] = useState("Eine klare Vorschau-Beschreibung."), [url, setUrl] = useState("https://www.example.de/seite"), [image, setImage] = useState("https://www.example.de/og.jpg"); const output = `<meta property="og:type" content="website">\n<meta property="og:title" content="${esc(title)}">\n<meta property="og:description" content="${esc(desc)}">\n<meta property="og:url" content="${esc(url)}">\n<meta property="og:image" content="${esc(image)}">\n<meta name="twitter:card" content="summary_large_image">`; return <><div className="field-grid"><Field label="Titel" value={title} onChange={setTitle} type="text" /><Field label="Seiten-URL" value={url} onChange={setUrl} type="url" /><Field label="Bild-URL" value={image} onChange={setImage} type="url" /><Field label="Beschreibung" value={desc} onChange={setDesc} type="text" /></div><div className="social-preview"><div aria-hidden="true">Vorschaubild · 1200 × 630 empfohlen</div><small>{url.replace(/^https?:\/\//, "").split("/")[0]}</small><strong>{title}</strong><p>{desc}</p></div><CodeResult value={output} /></>; }

function Robots() { const [agent, setAgent] = useState("*"), [blocked, setBlocked] = useState("/intern/\n/suche/"), [allowed, setAllowed] = useState(""), [sitemap, setSitemap] = useState("https://www.example.de/sitemap.xml"); const cleanLines = (v: string) => v.split("\n").map((x) => x.trim()).filter(Boolean); const output = [`User-agent: ${agent || "*"}`, ...cleanLines(allowed).map((x) => `Allow: ${x.startsWith("/") ? x : `/${x}`}`), ...cleanLines(blocked).map((x) => `Disallow: ${x.startsWith("/") ? x : `/${x}`}`), "", sitemap ? `Sitemap: ${sitemap}` : ""].filter((x, i, a) => x || a[i - 1] !== "").join("\n"); return <><div className="field-grid"><Field label="User-agent" value={agent} onChange={setAgent} type="text" /><Field label="Sitemap-URL" value={sitemap} onChange={setSitemap} type="url" /></div><div className="field-grid"><Area label="Gesperrte Pfade – einer pro Zeile" value={blocked} onChange={setBlocked} rows={6} /><Area label="Explizit erlaubte Pfade – optional" value={allowed} onChange={setAllowed} rows={6} /></div><p className="status-line warn">robots.txt ist kein Zugriffsschutz. Geheime Inhalte müssen serverseitig geschützt werden.</p><CodeResult value={output} /></>; }

function Sitemap() { const [input, setInput] = useState("https://www.example.de/\nhttps://www.example.de/ueber-uns\nhttps://www.example.de/kontakt"), [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const raw = [...new Set(input.split("\n").map((x) => x.trim()).filter(Boolean))], valid = raw.filter((x) => { try { const u = new URL(x); return u.protocol === "https:" || u.protocol === "http:"; } catch { return false; } }); const output = `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${valid.map((u) => `  <url>\n    <loc>${esc(u)}</loc>${date ? `\n    <lastmod>${date}</lastmod>` : ""}\n  </url>`).join("\n")}\n</urlset>`; const download = () => { const a = document.createElement("a"); a.href = URL.createObjectURL(new Blob([output], { type: "application/xml" })); a.download = "sitemap.xml"; a.click(); setTimeout(() => URL.revokeObjectURL(a.href), 0); }; return <><Area label="Absolute URLs – eine pro Zeile" value={input} onChange={setInput} rows={9} /><Field label="Letzte Änderung (optional)" value={date} onChange={setDate} type="date" /><p className={`status-line ${valid.length === raw.length ? "ok" : "warn"}`}>{valid.length} gültige URL{valid.length === 1 ? "" : "s"}; {raw.length - valid.length} ungültig</p><div className="tool-actions"><button className="secondary-button" onClick={() => copy(output)}>XML kopieren</button><button className="primary-button" onClick={download}>sitemap.xml herunterladen</button></div><CodeResult value={output} /></>; }

function Hreflang() { const [input, setInput] = useState("de-DE | https://www.example.de/seite\nen-GB | https://www.example.com/page\nx-default | https://www.example.com/page"); const entries = input.split("\n").map((x) => x.split("|").map((v) => v.trim())).filter(([lang, url]) => /^(x-default|[a-z]{2}(?:-[A-Z]{2})?)$/.test(lang) && /^https?:\/\//.test(url)); const output = entries.map(([lang, url]) => `<link rel="alternate" hreflang="${lang}" href="${esc(url)}">`).join("\n"); return <><Area label="Eine Version pro Zeile: Sprachcode | absolute URL" value={input} onChange={setInput} rows={8} /><p className={`status-line ${entries.length >= 2 ? "ok" : "warn"}`}>{entries.length} gültige Versionen. Füge diesen vollständigen Satz auf jeder aufgeführten Seite ein.</p><CodeResult value={output} /></>; }

export function LearningTextSeoRunner({ slug }: { slug: string }) { const content: Record<string, React.ReactNode> = { "notenrechner-gewichtung": <WeightedGrades />, "notenschluessel-rechner": <GradeKey />, "punkte-in-note-rechner": <GradeKey single />, bruchrechner: <Fractions />, gleichungsrechner: <Equation />, "lernplan-rechner": <LearningPlan />, "karteikarten-generator": <Flashcards />, lesbarkeitsanalyse: <Readability />, textvergleich: <TextDiff />, "fuellwort-finder": <Fillers />, textbereiniger: <Cleaner />, "gross-kleinschreibung": <LetterCase />, "quellenangaben-generator": <Citation />, "google-snippet-vorschau": <Snippet />, "keyworddichte-analyse": <KeywordDensity />, "onpage-seo-pruefer": <Onpage />, "seo-slug-generator": <Slug />, "meta-tag-generator": <MetaTags />, "faq-schema-generator": <FaqSchema />, "open-graph-generator": <OpenGraph />, "robots-txt-generator": <Robots />, "sitemap-generator": <Sitemap />, "hreflang-generator": <Hreflang /> }; return <>{content[slug]}</>; }
